### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by hodyroff**
clarified new setting to assure admin users can't see groups
add to the note that there can be as many group owners as you like
change name from group admin to group owner as thats what the UI has

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM

**Comment by mmattel** [comment]
When I started reviewing, I wondered where in config.php settings can be changed and wanted to link to the relevant section. Then I identified, that there is **no setting documented for custom groups**.

What I identified in the source code is the following:
There are settings that can be set via **occ commands**:

**config:app:set|get**
* `customgroups`, `only_subadmin_can_create` (true/false)
* `customgroups`, `allow_duplicate_names` (true/false)
* `core`, `shareapi_only_share_with_group_members` (yes/no)

**config:system:get|set**
* `customgroups`, `disallowed-groups` (string)
* `customgroups`, `disallow-admin-access-all` (true/false)

Before we are going to merge this PR, we have to document the corresponding occ commands for _custom groups_ in the [occ command app section](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#apps-commands). Then we are able to add a link in this document and merge it.

**Comment by jnweiger** [comment]
Example:

`occ config:system:set customgroups disallowed-groups --value huibuh`

Inspect /var/www/owncloud/config/config.php, it contains:
``` 
  'customgroups' =>
  array (
    'disallowed-groups' => 'huibuh',
  ),
);
```

We need to know the format of the string: Is it space-separated, comma-separated, or is it actually an array syntax in config.php with multiple string?

**Comment by mmattel** [comment]
Some small text corrections and a link to the proper section in server for changing default settings.

**Review by mmattel — APPROVED** [review]

**Pull request merged**
