### PR TITLE
Revert PR 34

### PR DESCRIPTION
**Pull request by phil-davis**
PR https://github.com/owncloud/core/pull/38775 fixed this behavior, released in ownCloud core 10.8.0.
The ExpireSharesJob now correctly only removes shares that have an expiration date of yesterday or before. Shares that expire on the current day are left in-place, because they need to work until the very end of the day.

So, IMO, the previous text was correct.

### CODE REVIEW

**Comment by NannaBarz** [comment]
Yes the share expired after the specific date but not at 0:01. He expires when the ExpireShareJob runs which can be at any time on the following day.
Some customers expect that the share expire at 0:01 so we need to describe it better.
The ExpireShareJob runs only one time per day so the time when he runs depends on the time when he first runs.
When this was 3pm the share is available till the next day 3pm.

**Comment by phil-davis** [comment]
@NannaBarz that was also fixed some time ago. Whenever a share is attempted to be accessed, the server validates the access attempt in real-time. If it is after the end of the expiration date (at 00:00:01 and after on the next day) the server removes the share in real-time and responds to the request with 404 "not found".

If you can demonstrate that this does not work correctly on ownCloud core 10.8.0 onwards, then please raise an issue.

**Comment by mmattel** [comment]
Could a clarifying statement be made if the revert is valid or not so we can proceed?

**Comment by phil-davis** [comment]
I believe that, in current oC10 releases, shares correctly stop working at the end of the expiration date. That is what the original text said. If someone can show that there is a problem, then please give a scenario of steps to demonstrate the problem - then we can write some text about what the problem is, get it fixed in the next release,...

**Review by mmattel — APPROVED** [review]

**Pull request merged**
